### ISSUE TITLE
Consider licensing the code snippets on the blog

### ISSUE THREAD

**Issue by pavloconuve** [comoyo/blog.telenor.io#4]
It would be beneficial for the software development community if the code snippets were available under some open-source licence, like MIT. E.g., a statement could be added to the blog's footer:

> © 2015 Telenor Digital. Powered by Jekyll using the HPSTR Theme.
> All code snippets are available under [MIT license](https://opensource.org/licenses/MIT).

**Comment by janjongboom** [comment]
@ksimons

**Comment by ksimons** [comment]
Fixed in 78ffe3e53fa4622ab9a811457a71d9de44423d3a among others.

**Comment by pavloconuve** [comment]
:thumbsup:
